### ISSUE TITLE
Extract phenological metrics from time series

### ISSUE THREAD

**Issue by yiluansong** [zhulabgroup/phenology-forecast#2]
- [x] Run their [tutorial](https://greenbrown.r-forge.r-project.org/man/Phenology.html)
- [x] Test with our MODIS data

**Comment by yiluansong** [comment]
ee8470a800c98241fd4f436f7a429716244961a1

**Comment by yiluansong** [comment]
@ziyuzhou0116 Try three methods for extracting methods and visualize.
@yiluansong read about their differences.

**Comment by yiluansong** [comment]
@ziyuzhou0116 Try double logistic for tspp [FitDoubleLogElmore](https://greenbrown.r-forge.r-project.org/man/FitDoubleLogElmore.html)

**Comment by ziyuzhou0116** [comment]
> @ziyuzhou0116 Try double logistic for tspp [FitDoubleLogElmore](https://greenbrown.r-forge.r-project.org/man/FitDoubleLogElmore.html)

b99315f312391c42fbb3b25c6db9c44579f8eda2

**Comment by ziyuzhou0116** [comment]
<img width="995" alt="截屏2023-04-14 下午5 06 26" src="https://user-images.githubusercontent.com/97424600/232156350-3a9dc619-140c-4531-a21f-c3e58db017cd.png">
